### PR TITLE
bubble_sort and bubble_sort_by methods for review

### PR DESCRIPTION
**Pull request by lucianosarno**
We have done the methods bubble_sort and bubble_sort_by as asked on the project requirements.

### CODE REVIEW

**Comment by AdesojiCodeMaster** [comment]
## This is to request the code review for our project;

### The Project Title:  **Sorting Arrays, Using the Methods bubble_sort and bubble_sort_by.**

### The Authors:  **Adesoji and Luciano **

[Live Demo Link](https://repl.it/repls/GreatIllSolaris#main.rb)

In this project, we  used;

### Ruby
### github/workflows

Thank You for taking the time to review our code. 💐

Thanks!

**Review by sumancrest0001 — APPROVED** [review]
**Status: APPROVED :100: :1st_place_medal: 
Congratulations TEAM :clap:** 

You have done a great job to make these methods as expected. All the test cases are passing. It is a YES from my side. Please go ahead and submit the project.

**Happy coding !!!**

**Comment by AdesojiCodeMaster** [comment]
**THANK FOR YOUR TIME.

**Comment by AdesojiCodeMaster** [comment]
**THANK YOU FOR YOUR TIME.**

**Pull request merged**
